name: Build, Test, and Package

on:
  push:
    branches:
      - develop
      - 'feat-*'

jobs:
  build:
    strategy:
       matrix:
         toolchain: [stable, beta, nightly]
         os: [ubuntu-latest, windows-latest, macOS-latest]
         workdir: [RektBroker, RektCommon]
         
    runs-on: ${{ matrix.os }}
  
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Update toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
        working-directory: ${{ matrix.workdir }}

      - name: Set up NASM
        # You may pin to the exact commit or the version.
        # uses: ilammy/setup-nasm@321e6ed62a1fc77024a3bd853deb33645e8b22c4
        uses: ilammy/setup-nasm@v1.4.0
        with:
          # NASM version to install
          version: 2.15.05
          platform: ${{ matrix.workdir }}
      
      - name: Build for ${{ matrix.os }}
        run: cargo build --release
        working-directory: ${{ matrix.workdir }}

      - name: Run Tests
        run: cargo test
        working-directory: ${{ matrix.workdir }}
