name: Rust

on:
  push:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build for Linux
      run: cargo build --release --target x86_64-unknown-linux-gnu

    - name: Build for Windows
      run: cargo build --release --target x86_64-pc-windows-msvc

    - name: Build for macOS
      run: cargo build --release --target x86_64-apple-darwin
    
    - name: Run tests
      run: cargo test --verbose


