name: Build, Test, and Package with Comment Coverage

on:
  push:
    branches:
      - develop
      - feat-**

defaults:
  run:
    working-directory: Sources

jobs:
  build:
    strategy:
       matrix:
         toolchain: [stable, beta, nightly]
         os: [ubuntu-latest, windows-latest, macOS-latest]
         
    runs-on: ${{ matrix.os }}
  
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Update toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Build for ${{ matrix.os }}
        run: cargo build --release

      - name: Run Tests
        run: cargo test
