name: Build and Package

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Rust
        uses: actions/setup-rust@v1

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build for Linux
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Build for Windows
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Build for macOS
        run: cargo build --release --target x86_64-apple-darwin

      - name: Create Zip File
        run: zip -r RekTBroker.zip target/release/*

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: RekTBroker
          path: RekTBroker.zip
